//! Linux seccomp sandbox (opt-in feature).
//!
//! When enabled via `--sandbox`, restricts the child process's system calls
//! to a safe subset using a seccomp BPF filter. Non-Linux platforms
//! gracefully degrade to a no-op.
//!
//! TODO: Integrate with `libseccomp` crate for BPF bytecode generation.
//! The allowed syscall list below is defined but not yet enforced at
//! the BPF level — it serves as documentation and future integration point.

/// Check if seccomp is available on this system.
#[cfg(target_os = "linux")]
pub fn is_seccomp_available() -> bool {
    std::path::Path::new("/proc/sys/kernel/seccomp/actions_avail").exists()
}

#[cfg(not(target_os = "linux"))]
pub fn is_seccomp_available() -> bool {
    false
}

/// Struct placeholder for BPF filter instructions.
/// In production, this would be generated by libseccomp or raw BPF.
#[cfg(target_os = "linux")]
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct sock_filter {
    pub code: u16,
    pub jt: u8,
    pub jf: u8,
    pub k: u32,
}

/// Build a seccomp BPF filter that blocks dangerous syscalls.
/// Currently returns a descriptive error — integrate libseccomp
/// (`cargo add libseccomp`) for production use.
#[cfg(target_os = "linux")]
pub fn build_seccomp_filter_blocklist() -> Result<Vec<sock_filter>, String> {
    Err(
        "seccomp BPF filter requires libseccomp crate. \
         Install: `cargo add libseccomp`. \
         The policy definitions are ready for integration."
            .to_string(),
    )
}

#[cfg(not(target_os = "linux"))]
pub fn build_seccomp_filter_blocklist() -> Result<Vec<u8>, String> {
    Err("seccomp sandbox is only supported on Linux".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seccomp_availability_is_detectable() {
        let available = is_seccomp_available();
        if cfg!(target_os = "linux") {
            let _ = available; // May be false in Docker without privileges
        } else {
            assert!(!available, "seccomp should not be available on non-Linux");
        }
    }

    #[test]
    #[cfg(target_os = "linux")]
    fn filter_policy_defined() {
        let result = build_seccomp_filter_blocklist();
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("libseccomp"));
    }
}
